// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  region: 'us-east-1',
  aws_project_region: 'us-east-1',
  userPoolId: 'us-east-1_42Z5mCThl',
  userPoolWebClientId: '4r83io36djl77qfea8r8s6kg2t'
}

export default awsmobile
